version: '2'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - server
      - client
    volumes:
       - ./nginx/conf.d:/etc/nginx/conf.d
       - ./client:/var/www
    environment:
      VIRTUAL_HOST: memo.0823.work
      LETSENCRYPT_HOST: memo.0823.work
      LETSENCRYPT_EMAIL: yuki.hayakawa0823@gmail.com
    restart: always
  server:
    image: node:9.8-alpine
    container_name: server
    volumes:
      - ./server:/src
      - ./config:/config
    working_dir: /src
    command: [sh, -c, yarn install && yarn build && yarn start]
    ports:
      - "3030:3030"
    restart: always
  client:
    image: node:9.8-alpine
    container_name: client
    volumes:
      - ./client:/src
      - ./config:/config
    working_dir: /src
    command: [sh, -c, yarn install && yarn build]
networks:
  default:
    external:
      name: nginxproxy_default
