version: '3.3'
services:
  nginx:
    build: ./nginx
    container_name: markdown-memo-nginx
    depends_on:
      - server
      - client
    volumes:
       - ./nginx/conf.d:/etc/nginx/conf.d
       - ./client:/var/www
    environment:
      VIRTUAL_HOST: ${HOST:-localhost}
      LETSENCRYPT_HOST: ${HOST:-localhost}
      LETSENCRYPT_EMAIL: ${EMAIL:-hoge@hoge.com}
    restart: always
  server:
    image: node:8.11-alpine
    container_name: markdown-memo-server
    env_file: .env
    volumes:
      - ./server:/src
      - ./.env:/.env
    working_dir: /src
    command: [sh, -c, yarn install && yarn build && yarn start]
    ports:
      - "3030:3030"
    restart: always
  client:
    image: node:8.11-alpine
    container_name: markdown-memo-client
    env_file: .env
    volumes:
      - ./client:/src
      - ./.env:/.env
    working_dir: /src
    command: [sh, -c, yarn install && yarn build]
networks:
  default:
    external:
      name: nginxproxy_default
